name: interview_prep
description: "E commerce"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  
  lottie: ^3.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_vertexai: ^2.2.0
  firebase_ai: ^3.4.0
  speech_to_text: ^7.0.0
  pdf: ^3.10.8
  printing: ^5.11.1
  google_fonts: ^6.3.2
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.0.15
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ai_intro.json
    - assets/aiai.json
    - assets/laptopp.png
    - assets/phone.png
    - assets/mouse.png
    - assets/keyboard.png
    - assets/monitor.png
    - assets/webcam.png
    - assets/tshirt.png
    - assets/hoodie.png
    - assets/shoes.png
    - assets/racket.png
    - assets/football.png
    - assets/yogamat.png
    - assets/smartwatch.png
    - assets/headphones.png

